### ISSUE TITLE
Linux: Could not determine host triple

### ISSUE THREAD

**Issue by apahl** [google/swift-jupyter#103]
Hi,

thanks a lot for providing an awesome tool for Swift for Tensorflow.

On Ubuntu 19.10, I am running the latest Swift for Tensorflow toolchain from [here](https://github.com/tensorflow/swift/blob/master/Installation.md#pre-built-packages). I can install packages, compile and run programs with it just fine.

I installed Swift-jupyter via the `conda` route.

When I try to execute a first cell that contains install instructions, like this one:

```
%install '.package(url: "https://github.com/vojtamolda/Plotly.swift.git", .exact("0.2.0"))' Plotly
%include "EnableIPythonDisplay.swift"
```

I get the following error:

```
Installing packages:
	.package(url: "https://github.com/vojtamolda/Plotly.swift.git", .exact("0.2.0"))
		Plotly
With SwiftPM flags: []
Working in: /tmp/tmprpl_p8ja/swift-install
Fatal error: could not determine host triple: malformed: file /swift-base/swiftpm/Sources/SPMBuildCore/Triple.swift, line 149

Install Error: swift-build returned nonzero exit code -4.

```

Again, using the toolchain manually, installing packages and building programs using the Swift Package Manager (SPM) works.

I also had a look at the `Triple.swift` file from SPM and I don't understand why it should fail, since the reported triple from `swift -print-target-info` is:

```
{
  "target": {
    "triple": "x86_64-unknown-linux-gnu",
    "unversionedTriple": "x86_64-unknown-linux-gnu",
    "moduleTriple": "x86_64-unknown-linux-gnu",
    "librariesRequireRPath": false
  },
  "paths": {
    "runtimeLibraryPaths": [
      "/home/pahl/progs/swift/usr/lib/swift/linux"
    ],
    "runtimeLibraryImportPaths": [
      "/home/pahl/progs/swift/usr/lib/swift/linux/x86_64"
    ],
    "runtimeResourcePath": "/home/pahl/progs/swift/usr/lib/swift"
  }
}
```

which should be fine.

Many thanks in advance for your help.

Kind regards,  
Axel

**Comment by apahl** [comment]
The problem was that the version of libtinfo that was installed with `conda` does not have version information included.
This let to a compiler warning 

`/home/pahl/anaconda3/envs/swift/lib/libtinfo.so.6: no version information available (required by bash)`

which in turn messed up the target info output.

Solution:  
removed the conda `libtinfo.so.6.1` and created a symlink to the system `/lib/x86_64-linux-gnu/libtinfo.so.6.1`

**Comment by marcrasi** [comment]
This exact thing has happened to me before, with a different shared library!

We could prevent this from happening by making the SwiftPM parser more robust to these warning messages, here: https://github.com/apple/swift-package-manager/blob/3e551dcd3678b9e10c6a9db2752cfdc5194e871c/Sources/SPMBuildCore/Triple.swift#L136 . I'll file a ticket and/or a PR against SwiftPM soon.
