### ISSUE TITLE
How SWIFT_IMPORT_SEARCH_PATH supported in Python enabled LLDB

### ISSUE THREAD

**Issue by liuliu** [google/swift-jupyter#119]
Hey, all.

Thanks for the great work on Swift Jupyter. I am trying to figure out how to compile latest Swift 5.3 with Python LLDB support without going off Swift for TensorFlow branch. So far, it worked well except the SWIFT_IMPORT_SEARCH_PATH bit. It appears that has no impact for the apple/llvm-project at `release/5.3`. I am wondering how this is implemented and whether we can port it over to the mainline. Thanks!

**Comment by liuliu** [comment]
nvm, found it: https://github.com/apple/llvm-project/blob/swift/tensorflow/lldb/source/Plugins/TypeSystem/Swift/SwiftASTContext.cpp#L2596 I was looking at wrong branch.

Any idea whether we can upstream this to mainline?

**Comment by liuliu** [comment]
After some digging, I found the upstream recently moved to `settings target.swift-module-search-paths` in the debugger command. Hence, we should be able to remove the `parent_kernel.py / swift_kernel.py` dance and also just add `self.debugger.HandleCommand("settings append target.swift-module-search-paths " + swift_import_search_path)` when initializing the debugger.

If you like, I can put up a PR with the said change.

**Comment by marcrasi** [comment]
If that works, it would be amazing. I do want swift-jupyter to work on the mainline Swift branch eventually, but I haven't had any time to make progress on that. Any incremental progress would be great!

**Comment by marcrasi** [comment]
Fixed in #120.
